version = 1

[[annotations]]
path = [
    "depends/netlistsvg/package-lock.json",
    "src/include/gamma_5bit.svh",
    "src/include/gamma_6bit.svh",
    "src/include/gamma_8bit.svh"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".pre-commit-config.yaml",
    ".toolchain-version",
    ".python-requirements",
    ".verilator_lint",
    ".vscode/settings.json",
    ".devcontainer/devcontainer.json",
    ".python-version"
]
SPDX-FileCopyrightText = "2025 Aaron White <w531t4@gmail.com>"
SPDX-License-Identifier = "MIT"
