version = 1

[[annotations]]
path = [
    "depends/netlistsvg/package-lock.json"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".pre-commit-config.yaml",
    ".python-requirements",
    ".python-version"
]
SPDX-FileCopyrightText = "2025 Aaron White <w531t4@gmail.com>"
SPDX-License-Identifier = "MIT"
